///////////////////////////////////////////////////////////////////
         //////                                    //////
///////////////////////////////////////////////////////////////////
///                                                             ///
/// This file is generated by Viterbi HDL Code Generator(VHCG)  ///
/// which is written by Mike Johnson at OpenCores.org  and      ///
/// distributed under GPL license.                              ///
///                                                             ///
/// If you have any advice,                                     ///
/// please email to jhonson.zhu@gmail.com                       ///
///                                                             ///
///////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////




`timescale 1ns/1ps
`define SM_Width 8 
`define Bit_Width 4 
`define BM_Width 4 
`define SYMBOLS_NUM 2
`define MAX_INPUT 7
`define MAX_PM 156

`define RAM_BYTE_WIDTH  32 
`define RAM_ADR_WIDTH 	8 //10

`define U 1
`define V 1
`define W 4



`define BIG 1           // the width of big slice

// add by moti
// secret debug flag 
//`define DEBUG				1
//`define DEBUG_OUT_FILE		"sim_out/f_debug.txt" 
