///////////////////////////////////////////////////////////////////
         //////                                    //////
///////////////////////////////////////////////////////////////////
///                                                             ///
/// This file is generated by Viterbi HDL Code Generator(VHCG)  ///
/// which is written by Mike Johnson at OpenCores.org  and      ///
/// distributed under GPL license.                              ///
///                                                             ///
/// If you have any advice,                                     ///
/// please email to jhonson.zhu@gmail.com                       ///
///                                                             ///
///////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////



`include "glb_def.v"

`define MAX_SLICE 1                // 2^(`U)

// just for test, not support state-set division.   
module smu
(
	mclk, 
	rst,
	rst_tf,	
	valid, 
	wr_sm0, wr_sm1, 
	wr_tf0, wr_tf1,
	rd_sm0, rd_sm1,
	rd_tf0, rd_tf1,
	rd_tf0_output, rd_tf1_output
);

input mclk, rst, rst_tf, valid;
input[`SM_Width-1:0] wr_sm0, wr_sm1;
input[`W+`V+`U-1:0] wr_tf0, wr_tf1;
output[`SM_Width-1:0] rd_sm0, rd_sm1;
output[`W+`V+`U-1:0] rd_tf0, rd_tf1;
output [`W+`V+`U-1:0] rd_tf0_output, rd_tf1_output;

reg[`SM_Width-1:0] rd_sm0, rd_sm1;   ///////////////////////////////////////

reg[`W+`V+`U-1:0] rd_tf0, rd_tf1;

reg[`W+`V+`U-1:0] rd_tf0_output, rd_tf1_output;

integer i;
parameter PE_ID=0;

always @(posedge mclk or posedge rst)
begin
    if(rst)
    begin
		rd_sm0<='b0;
		rd_sm1<='b0;
		
		rd_tf0<='b0;
		rd_tf1<='b0;					
	end	
    else if(valid)
		begin
			rd_sm0<=wr_sm0;
			rd_sm1<=wr_sm1;
			if(rst_tf)
				begin
					rd_tf0<=PE_ID;
					rd_tf1<=PE_ID+32;
						
					rd_tf0_output<=wr_tf0;
					rd_tf1_output<=wr_tf1;					
				end
			else
				begin
					rd_tf0<=wr_tf0;
					rd_tf1<=wr_tf1;			
				end
				
			
		end	
		
end

endmodule
